//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ConsumeWebService.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ContactLessQRCodeWithdrawalServiceSoap", Namespace="http://tempuri.org/")]
    public partial class ContactLessQRCodeWithdrawalService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private AuthenticationHeader authenticationHeaderValueField;
        
        private System.Threading.SendOrPostCallback GenerateQRCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidateQRCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidateQROTPOperationCompleted;
        
        private System.Threading.SendOrPostCallback DispenseCashOperationCompleted;
        
        private System.Threading.SendOrPostCallback TxnCancelOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateTransactionStatusOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ContactLessQRCodeWithdrawalService() {
            this.Url = global::ConsumeWebService.Properties.Settings.Default.ConsumeWebService_localhost_ContactLessQRCodeWithdrawalService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public AuthenticationHeader AuthenticationHeaderValue {
            get {
                return this.authenticationHeaderValueField;
            }
            set {
                this.authenticationHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GenerateQRCodeCompletedEventHandler GenerateQRCodeCompleted;
        
        /// <remarks/>
        public event ValidateQRCodeCompletedEventHandler ValidateQRCodeCompleted;
        
        /// <remarks/>
        public event ValidateQROTPCompletedEventHandler ValidateQROTPCompleted;
        
        /// <remarks/>
        public event DispenseCashCompletedEventHandler DispenseCashCompleted;
        
        /// <remarks/>
        public event TxnCancelCompletedEventHandler TxnCancelCompleted;
        
        /// <remarks/>
        public event UpdateTransactionStatusCompletedEventHandler UpdateTransactionStatusCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GenerateQRCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GenerateQRCode(string InputJsonMessage) {
            object[] results = this.Invoke("GenerateQRCode", new object[] {
                        InputJsonMessage});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GenerateQRCodeAsync(string InputJsonMessage) {
            this.GenerateQRCodeAsync(InputJsonMessage, null);
        }
        
        /// <remarks/>
        public void GenerateQRCodeAsync(string InputJsonMessage, object userState) {
            if ((this.GenerateQRCodeOperationCompleted == null)) {
                this.GenerateQRCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenerateQRCodeOperationCompleted);
            }
            this.InvokeAsync("GenerateQRCode", new object[] {
                        InputJsonMessage}, this.GenerateQRCodeOperationCompleted, userState);
        }
        
        private void OnGenerateQRCodeOperationCompleted(object arg) {
            if ((this.GenerateQRCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GenerateQRCodeCompleted(this, new GenerateQRCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidateQRCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ValidateQRCode(string InputJsonMessage) {
            object[] results = this.Invoke("ValidateQRCode", new object[] {
                        InputJsonMessage});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ValidateQRCodeAsync(string InputJsonMessage) {
            this.ValidateQRCodeAsync(InputJsonMessage, null);
        }
        
        /// <remarks/>
        public void ValidateQRCodeAsync(string InputJsonMessage, object userState) {
            if ((this.ValidateQRCodeOperationCompleted == null)) {
                this.ValidateQRCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateQRCodeOperationCompleted);
            }
            this.InvokeAsync("ValidateQRCode", new object[] {
                        InputJsonMessage}, this.ValidateQRCodeOperationCompleted, userState);
        }
        
        private void OnValidateQRCodeOperationCompleted(object arg) {
            if ((this.ValidateQRCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateQRCodeCompleted(this, new ValidateQRCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidateQROTP", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ValidateQROTP(string InputJsonMessage) {
            object[] results = this.Invoke("ValidateQROTP", new object[] {
                        InputJsonMessage});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ValidateQROTPAsync(string InputJsonMessage) {
            this.ValidateQROTPAsync(InputJsonMessage, null);
        }
        
        /// <remarks/>
        public void ValidateQROTPAsync(string InputJsonMessage, object userState) {
            if ((this.ValidateQROTPOperationCompleted == null)) {
                this.ValidateQROTPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateQROTPOperationCompleted);
            }
            this.InvokeAsync("ValidateQROTP", new object[] {
                        InputJsonMessage}, this.ValidateQROTPOperationCompleted, userState);
        }
        
        private void OnValidateQROTPOperationCompleted(object arg) {
            if ((this.ValidateQROTPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateQROTPCompleted(this, new ValidateQROTPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DispenseCash", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DispenseCash(string InputJsonMessage) {
            object[] results = this.Invoke("DispenseCash", new object[] {
                        InputJsonMessage});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DispenseCashAsync(string InputJsonMessage) {
            this.DispenseCashAsync(InputJsonMessage, null);
        }
        
        /// <remarks/>
        public void DispenseCashAsync(string InputJsonMessage, object userState) {
            if ((this.DispenseCashOperationCompleted == null)) {
                this.DispenseCashOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDispenseCashOperationCompleted);
            }
            this.InvokeAsync("DispenseCash", new object[] {
                        InputJsonMessage}, this.DispenseCashOperationCompleted, userState);
        }
        
        private void OnDispenseCashOperationCompleted(object arg) {
            if ((this.DispenseCashCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DispenseCashCompleted(this, new DispenseCashCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TxnCancel", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TxnCancel(string InputJsonMessage) {
            object[] results = this.Invoke("TxnCancel", new object[] {
                        InputJsonMessage});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TxnCancelAsync(string InputJsonMessage) {
            this.TxnCancelAsync(InputJsonMessage, null);
        }
        
        /// <remarks/>
        public void TxnCancelAsync(string InputJsonMessage, object userState) {
            if ((this.TxnCancelOperationCompleted == null)) {
                this.TxnCancelOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTxnCancelOperationCompleted);
            }
            this.InvokeAsync("TxnCancel", new object[] {
                        InputJsonMessage}, this.TxnCancelOperationCompleted, userState);
        }
        
        private void OnTxnCancelOperationCompleted(object arg) {
            if ((this.TxnCancelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TxnCancelCompleted(this, new TxnCancelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateTransactionStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpdateTransactionStatus(string InputJsonMessage) {
            object[] results = this.Invoke("UpdateTransactionStatus", new object[] {
                        InputJsonMessage});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateTransactionStatusAsync(string InputJsonMessage) {
            this.UpdateTransactionStatusAsync(InputJsonMessage, null);
        }
        
        /// <remarks/>
        public void UpdateTransactionStatusAsync(string InputJsonMessage, object userState) {
            if ((this.UpdateTransactionStatusOperationCompleted == null)) {
                this.UpdateTransactionStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateTransactionStatusOperationCompleted);
            }
            this.InvokeAsync("UpdateTransactionStatus", new object[] {
                        InputJsonMessage}, this.UpdateTransactionStatusOperationCompleted, userState);
        }
        
        private void OnUpdateTransactionStatusOperationCompleted(object arg) {
            if ((this.UpdateTransactionStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateTransactionStatusCompleted(this, new UpdateTransactionStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class AuthenticationHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string usernameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GenerateQRCodeCompletedEventHandler(object sender, GenerateQRCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GenerateQRCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GenerateQRCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ValidateQRCodeCompletedEventHandler(object sender, ValidateQRCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateQRCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateQRCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ValidateQROTPCompletedEventHandler(object sender, ValidateQROTPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateQROTPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateQROTPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void DispenseCashCompletedEventHandler(object sender, DispenseCashCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DispenseCashCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DispenseCashCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void TxnCancelCompletedEventHandler(object sender, TxnCancelCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TxnCancelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TxnCancelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void UpdateTransactionStatusCompletedEventHandler(object sender, UpdateTransactionStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateTransactionStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateTransactionStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591